services:
  app:
    build: .
    container_name: laravel_api
    ports:
      - "8000:80"  
    volumes:
      - .:/var/www/html 
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3308
      - DB_DATABASE=tests
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db 

  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"  
    volumes:
      - mariadb_data:/var/lib/mysql  

volumes:
  mariadb_data: